export const products = [
  {
    id: 1,
    name: "Loveseat Sofa",
    price: "199.00",
    oldPrice: "400.00",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "loveseat-sofa.jpg",
  },
  {
    id: 2,
    name: "Luxury Sofa",
    price: "299.00",
    oldPrice: "500.00",
    discount: "50%",
    rating: 5,
    description: "lorem lorem lorem lorem lorem lorem",
    isNew: true,
    image: "luxury-sofa.jpg",
  },
  {
    id: 3,
    name: "Table Lamp",
    price: "19.00",
    oldPrice: "38.00",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "table-lamp.jpg",
  },
  {
    id: 4,
    name: "White Drawer Unit",
    price: "89.99",
    oldPrice: "180.00",
    discount: "50%",
    description: "lorem lorem lorem lorem lorem lorem",
    rating: 5,
    isNew: true,
    image: "white-drawer-unit.jpg",
  },
  {
    id: 5,
    name: "Black Tray Table",
    price: "19.99",
    oldPrice: "39.99",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "black-tray-table.jpg",
  },
  {
    id: 6,
    name: "Bamboo Basket",
    price: "9.50",
    oldPrice: "19.00",
    description: "lorem lorem lorem lorem lorem lorem",
    discount: "50%",
    rating: 5,
    isNew: true,
    image: "bamboo-basket.jpg",
  },
  {
    id: 7,
    name: "Off-White Pillow",
    price: "7.99",
    oldPrice: "15.99",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "off-white-pillow.jpg",
  },
  {
    id: 8,
    name: "Light Beige Pillow",
    price: "3.99",
    oldPrice: "7.99",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "light-beige-pillow.jpg",
  },
  {
    id: 9,
    name: "Black Brow Side Table",
    price: "16.99",
    oldPrice: "33.99",
    discount: "50%",
    rating: 5,
    description: "lorem lorem lorem lorem lorem lorem",
    isNew: true,
    image: "black-brow-side-table.jpg",
  },
  {
    id: 10,
    name: "Cozy Sofa",
    price: "229.00",
    oldPrice: "460.00",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "cozy-sofa.jpg",
  },
  {
    id: 11,
    name: "Modern Chair",
    price: "149.00",
    oldPrice: "298.00",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "modern-chair.jpg",
  },
  {
    id: 12,
    name: "Floor Lamp",
    price: "89.00",
    oldPrice: "178.00",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "floor-lamp.jpg",
  },
  {
    id: 13,
    name: "Round Coffee Table",
    price: "59.99",
    oldPrice: "119.99",
    discount: "50%",
    rating: 5,
    isNew: true,
    description: "lorem lorem lorem lorem lorem lorem",
    image: "round-coffee-table.jpg",
  },
  {
    id: 14,
    name: "Office Chair",
    price: "129.00",
    oldPrice: "258.00",
    discount: "50%",
    description: "lorem lorem lorem lorem lorem lorem",
    rating: 5,
    isNew: true,
    image: "office-chair.jpg",
  },
];
